name: Publish Docker image
on: workflow_dispatch

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            appknox/minio-gh-workflow
          tags: |
            type=raw,value=${{ github.ref_name }},enable={{is_default_branch}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      